/* @module src/sheet */

import Handsontable from 'handsontable'

import { columns } from './columns'

/* The sheet (with all it's configurations). */
export const sheet = new Handsontable(document.getElementById('sheet')!, {
  allowEmpty: true,
  allowHtml: false,
  allowInsertColumn: false,
  allowInsertRow: false,
  allowRemoveColumn: false,
  allowRemoveRow: false,
  autoColumnSize: true,
  autoRowSize: true,
  autoWrapCol: false,
  autoWrapRow: false,
  bindRowsWithHeaders: true,
  colHeaders: true,
  collapsibleColumns: false,
  columns: columns,
  columnSorting: true,
  comments: false,
  contextMenu: false,
  copyable: false,
  copyPaste: false,
  correctFormat: false,
  customBorders: false,
  data: [],
  disableVisualSelection: true,
  dragToScroll: false,
  dropdownMenu: false,
  editor: false,
  enterBeginsEditing: false,
  fillHandle: false,
  filter: false,
  filters: true,
  fixedColumnsStart: 1,
  fixedRowsTop: 1,
  fragmentSelection: false,
  //height: 500,
  hiddenColumns: false,
  hiddenRows: false,
  language: 'en-US',
  layoutDirection: 'inherit',
  licenseKey: 'non-commercial-and-evaluation',
  //locale: 'en-US',
  manualColumnFreeze: false,
  manualColumnMove: false,
  manualColumnResize: false,
  manualRowMove: false,
  manualRowResize: false,
  mergeCells: false,
  multiColumnSorting: false,
  //nestedHeaders: false,
  nestedRows: false,
  observeDOMVisibility: true,
  outsideClickDeselects: true,
  persistentState: false,
  preventOverflow: false,
  readOnly: true,
  renderAllRows: true,
  rowHeaders: true,
  search: false,
  selectionMode: 'single',
  skipColumnOnPaste: false,
  skipRowOnPaste: false,
  sortByRelevance: false,
  strict: true,
  trimDropdown: true,
  trimRows: false,
  trimWhitespace: true,
  uncheckedTemplate: false,
  undo: false,
  viewportColumnRenderingOffset: 'auto',
  viewportRowRenderingOffset: 'auto',
  //width: 300,
  wordWrap: false,
})
